# Generated by Django 3.0.7 on 2020-06-23 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('year_in_school', models.CharField(choices=[('TR', 'Turkey'), ('US', 'United States'), ('FR', 'France'), ('ES', 'Spain'), ('IT', 'Italy')], default='TR', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-points']},
        ),
        migrations.AlterField(
            model_name='player',
            name='country_iso_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard_app.Country'),
        ),
    ]
