# Generated by Django 3.0.7 on 2020-06-24 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('leaderboard_name', models.CharField(default='highscore', max_length=55)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-points']},
        ),
        migrations.AlterField(
            model_name='player',
            name='country_iso_code',
            field=models.CharField(choices=[('TR', 'Turkey'), ('US', 'United States'), ('FR', 'France'), ('ES', 'Spain'), ('IT', 'Italy')], max_length=2),
        ),
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='UserPoint',
        ),
        migrations.AddField(
            model_name='player',
            name='leaderboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leaderboard_app.LeaderBoard'),
        ),
    ]
