# Generated by Django 3.0.7 on 2020-06-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard_app', '0002_auto_20200623_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='country_iso_code',
            field=models.CharField(choices=[('TR', 'Turkey'), ('US', 'United States'), ('FR', 'France'), ('ES', 'Spain'), ('IT', 'Italy')], default='TR', max_length=2),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
