# Generated by Django 3.0.7 on 2020-06-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard_app', '0003_auto_20200623_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='country_iso_code',
            field=models.CharField(choices=[('TR', 'Turkey'), ('US', 'United States'), ('FR', 'France'), ('ES', 'Spain'), ('IT', 'Italy')], max_length=2),
        ),
    ]
