# Generated by Django 3.0.7 on 2020-06-24 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard_app', '0005_auto_20200624_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='next_player',
        ),
        migrations.RemoveField(
            model_name='player',
            name='rank',
        ),
    ]
