# Generated by Django 3.0.7 on 2020-06-24 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard_app', '0007_player_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='rank',
        ),
    ]
